In [1]:
## 1.Student marks array

import numpy as np
marks = np.array([78, 65, 89, 56, 92])
print("Marks:", marks)
print("Number of elements:", marks.size)
print("Shape:", marks.shape)
print("Dimension:", marks.ndim)
print("Data type:", marks.dtype)

Marks: [78 65 89 56 92]
Number of elements: 5
Shape: (5,)
Dimension: 1
Data type: int32


In [2]:
## 2. Student Marks Access

import numpy as np
marks = np.array([72, 85, 64, 90, 76])
print("Marks:", marks)
print("First student:", marks[0])
print("Third student:", marks[2])
print("Last student:", marks[-1])
print("First three students:", marks[:3])
print("Second to fourth students:", marks[1:4])

Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three students: [72 85 64]
Second to fourth students: [85 64 90]


In [3]:
## 3.Subject-wise Marks

import numpy as np
marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])
matrix = marks.reshape(5, 3)
print("Original array:")
print(marks)
print("\nMarks matrix:")
print(matrix)

Original array:
[78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]

Marks matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


In [4]:
## 4.Internal and External Marks

import numpy as np
internal = np.array([25, 22, 24, 20, 23])
external = np.array([65, 70, 68, 72, 69])
final_marks = internal + external
print("Internal marks:", internal)
print("External marks:", external)
print("Final marks:", final_marks)

Internal marks: [25 22 24 20 23]
External marks: [65 70 68 72 69]
Final marks: [90 92 92 92 92]


In [5]:
## 5.Pass Percentage Analysis

import numpy as np
marks = np.array([45, 78, 56, 32, 91])
passed = marks[marks >= 50]
print("Marks:", marks)
print("Students scoring 50 or above:", passed)

Marks: [45 78 56 32 91]
Students scoring 50 or above: [78 56 91]


In [6]:
## 6.Average Marks

import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
average = np.mean(marks, axis=1)
print("Marks:")
print(marks)
print("\nAverage marks of each student:")
print(average)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


In [7]:
## 7.Class Performance Statistics

import numpy as np
marks = np.array([67, 82, 91, 74, 58])
print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard deviation: 11.46472851837321


In [8]:
## 8.Subject-wise Performance

import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)

print("Marks:")
print(marks)

print("\nTotal marks in each subject:")
print(subject_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks in each subject:
[382 399 416]


In [9]:
## 9.Student-wise Performance

import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
student_total = np.sum(marks, axis=1)
print("Marks:")
print(marks)
print("\nTotal marks of each student:")
print(student_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks of each student:
[253 217 263 188 276]


In [10]:
## 10. Student Ranking

import numpy as np
marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)[::-1]
ranking = np.argsort(marks)[::-1]
print("Total marks:", marks)
print("\nMarks in descending order:")
print(sorted_marks)
print("\nStudent ranking:")
for i in range(len(ranking)):
    student = ranking[i] + 1
    print("Rank", i + 1, ": Student", student, "-", marks[ranking[i]])

Total marks: [245 278 219 290 256]

Marks in descending order:
[290 278 256 245 219]

Student ranking:
Rank 1 : Student 4 - 290
Rank 2 : Student 2 - 278
Rank 3 : Student 5 - 256
Rank 4 : Student 1 - 245
Rank 5 : Student 3 - 219


In [11]:
## 11. Duplicate Marks Analysis

import numpy as np
marks = np.array([85, 92, 85, 76, 92])
unique_marks = np.unique(marks)
print("Marks:", marks)
print("Unique marks:", unique_marks)

Marks: [85 92 85 76 92]
Unique marks: [76 85 92]


In [12]:
## 12. Missing Marks

import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average = np.nanmean(marks)

print("Marks:", marks)
print("Average without missing value:", average)

Marks: [78. 85. nan 92. 67.]
Average without missing value: 80.5


In [13]:
## 13. Grade Classification

import numpy as np
marks = np.array([95, 82, 74, 61, 45])
grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)
print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


In [14]:
## 14. Random Marks Geneartion import numpy as np

marks = np.random.randint(0, 101, 5)

print("Randomly generated marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Randomly generated marks: [38 72 78 13 51]
Total: 252
Average: 50.4
Highest: 78
Lowest: 13
Standard deviation: 23.58474082961269


In [15]:
## 15. Student Performance Analysis

import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)
class_average = np.mean(average)
print("Marks:")
print(marks)
print("\nTotal marks of each student:")
print(total)
print("\nAverage marks of each student:")
print(average)
print("\nHighest mark of each student:")
print(highest)
print("\nLowest mark of each student:")
print(lowest)
print("\nClass average:", class_average)
print("\nStudents performing above class average:")
for i in range(len(average)):
    if average[i] > class_average:
        print("Student", i + 1, "-", average[i])

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks of each student:
[253 217 263 188 276]

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]

Highest mark of each student:
[90 80 91 70 95]

Lowest mark of each student:
[78 65 84 56 89]

Class average: 79.8

Students performing above class average:
Student 1 - 84.33333333333333
Student 3 - 87.66666666666667
Student 5 - 92.0
